---
title: "Analysis"
format: html
execute: 
  echo: false
---

Using the nhanes data set from the NHN examination survey, we seek to create a model to predict male height. We do not know if representativeness can be assumed. We found height using an intercept-only regression model. we've found that around 3% of males will be 180 cm tall, although this has some uncertainty to it.

```{r,warning= FALSE}
#| label: setup
#| message: false
library(tidyverse)
library(primer.data)
library(skimr)
library(tidybayes)
library(brms)
library(gtsummary)
```

```{r}
nhanes|>
  filter(sex=="Male",
         age>=18)|>
    select(height)|>
      drop_na()|>
        ggplot(aes(x=height))+
        geom_histogram(bins=50)+
        labs(title="Male Adult Height in the US in 2010",
             x="Height (cm)",
             y="Count",
             caption="Source: National Health and Nutrition")
```

```{r}
#| cache: TRUE
fit_male_height<-brm(formula = height ~ 1, data = nhanes, family = gaussian(), silent = 2, refresh = 0, seed = 12)

```

```{r}
tbl_regression(fit_male_height,intercept=TRUE)

```

```{r}
#| label: plot
ndata <- tibble(.rows = 1)
fit_male_height|>
  add_predicted_draws(newdata = ndata)|>
    ggplot(aes(x=.prediction))+
    geom_histogram(aes(y=after_stat(count / sum(count))),bins=100)+
    labs(title="Probability of certain heights in males",
         subtitle="Centered around 175",
         x="Predicted height(cm)",y="Probability",
         caption="Data from NHN")+
    scale_y_continuous(labels=scales::percent_format(accuracy = 1))+
    scale_x_continuous(labels = scales::number_format())
```

```{r}
fit_male_height|>
  add_predicted_draws(newdata = ndata)|>
    mutate(tall=if_else(.prediction > 180, TRUE, FALSE))|>
      summarize(odds=mean(tall))
```

